# Generated by Django 5.2.5 on 2025-09-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_enrollment_payment_schedule_student_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='cpurse_id',
            new_name='course_id',
        ),
    ]
