# Generated by Django 5.2.5 on 2025-09-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_rename_cpurse_id_schedule_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='department',
            new_name='status',
        ),
    ]
